=== EdisonVaca01/1a-o--ASIR--Lenguaje-de-Marcas-y-Sistemas-de-Gestion-de-Informacion/3º Trimestre/XSD/alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bdalumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="alumno">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:integer" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="padre" type="xs:string" />
                            <xs:element name="madre" type="xs:string" />
                            <xs:element name="edad" type="xs:unsignedByte" />
                            <xs:element name="ciudad" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EdisonVaca01/1a-o--ASIR--Lenguaje-de-Marcas-y-Sistemas-de-Gestion-de-Informacion/3º Trimestre/XSD/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<bdalumnos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="alumnos.xsd">
    <alumno>
        <nombre id="1">sergio</nombre>
        <padre>antonio</padre>
        <madre>carmen</madre>
        <edad>18</edad>
        <ciudad>madrid</ciudad>
    </alumno>
    <alumno>
        <nombre id="2">pepe</nombre>
        <padre>luis</padre>
        <madre>ana</madre>
        <edad>20</edad>
        <ciudad>madrid</ciudad>
    </alumno>
</bdalumnos>
