=== EdisonVaca01/1a-o--ASIR--Lenguaje-de-Marcas-y-Sistemas-de-Gestion-de-Informacion/3º Trimestre/XSD/validacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Definimos el esquema donde también declaramos los elementos como los atributos que en este caso son qualified-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="ifp">
        <xs:complexType>
            <!-- Agregamos el xs:all ya que los hijos van a aparecer de la secuencia/orden de la que nosotros deseamos  -->
            <xs:all>
                <!--Agregamos el xs:element ya que es un elemento simple-->
                <xs:element name="autor">
                    <!-- Empezamos a definir elementos de tipo complejo donde posteriormente vamos a completarlo con un <xs:sequence> -->
                    <xs:complexType>
                        <!--Agregamos un xs:sequence donde especificamos los hijos del elemento principal-->
                        <xs:sequence>
                            <xs:element ref="nombre"></xs:element>
                            <xs:element name="apellidos">
                                <!-- Definimos elemento simple en este caso -->
                                <xs:simpleType>
                                    <!-- Agregamos un xs:restriction  para realizar una restricción en este caso del valor como de la base -->
                                    <xs:restriction base="xs:string">
                                        <xs:length value="14" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element ref="correo"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="modulos">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- En este caso en el xs:element  agregamos un minOccurs que es la vez mínima que  va a aparecer este elemento, es decir la mínima 1  y el maxOccurs el máximo de veces que va a ser 2-->
                            <xs:element name="curso" minOccurs="1" maxOccurs="2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- Algo nuevo que hemos realizado aquí es el maxOccurs="unbounded"en el que quiere decir que el valor máximo de aparación es ilimitada-->
                                        <xs:element name="modulo" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute ref="id"></xs:attribute>
                                                <xs:attribute ref="nombre"></xs:attribute>
                                                <xs:attribute ref="profesor"></xs:attribute>
                                                <xs:attribute ref="tecnologias"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute ref="nombre"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute ref="ciclo"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="profesores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="profesor" minOccurs="1" maxOccurs="3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <!-- Nosotros en esta caso estámos diciendo que los únicos valores admitidos son "Segio" "Naza" "Paco" -->
                                                    <xs:enumeration value="Sergio" />
                                                    <xs:enumeration value="Naza" />
                                                    <xs:enumeration value="Paco" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element ref="correo"></xs:element>
                                        <xs:element ref="materia"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id">
                                        <xs:simpleType>
                                            <!-- En la base de xs:restriction agregamos una "xs:integer" en lo que queremos decir es que son valores enteros -->
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1" />
                                                <xs:maxInclusive value="3" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <!--Atributos Realizados-->
    <xs:attribute name="ciclo" type="xs:string" default="ASIR"></xs:attribute>
    <xs:attribute name="nombre" type="xs:string"></xs:attribute>
    <xs:attribute name="id" type="xs:string"></xs:attribute>
    <xs:attribute name="profesor" type="xs:string"></xs:attribute>
    <xs:attribute name="tecnologias" type="xs:string"></xs:attribute>
    <!--Elementos Realizados-->
    <xs:element name="nombre" type="xs:string"></xs:element>
    <xs:element name="correo" type="xs:string"></xs:element>
    <xs:element name="materia" type="xs:string"></xs:element>
</xs:schema>

=== EdisonVaca01/1a-o--ASIR--Lenguaje-de-Marcas-y-Sistemas-de-Gestion-de-Informacion/3º Trimestre/XSD/modulos.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- En este apartado estamos dando en "enlace" al "conexión" a valdiar.dtd -->
<ifp xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="validacion.xsd">
        <!-- En este aparatado agregamos al autor de dicho trabajo-->
        <autor>
            <nombre>Edison Gabriel</nombre>
            <apellidos>Vaca Cifuentes</apellidos>
            <correo>iamedisonvaca@hotmail.com</correo>
        </autor>
        <!-- En este apartado estaremos agregando los 2 módulos "contenedor" -->
        <modulos ciclo="Administración en Sistemas Operativos y Redes">
            <!--Contenedor del primer curso -->
            <curso nombre="primero">
                <modulo id="MP01" nombre="Formación Orientación Laboral" profesor="Naza" tecnologias="Incorporación al trabajo, Prevención de riesgos laborales " />
                <modulo id="MP02" nombre="Fundamentos de Hardware" profesor="Paco" tecnologias="Arquitectura de sistemas, Instalación, configuración y recuperación de software,Implantación y mantenimiento de CPD" />
                <modulo id="MP03" nombre="Gestión  de Base de Datos" profesor="Paco" tecnologias="Introducción a las bases de datos,Gestión de seguridad de los datos" />
                <modulo id="MP04" nombre="Impltantación de Sistemas Operativos" profesor="Paco" tecnologias="Instalación, configuración y explotación del sistema informático, Gestión de la información y de recursos en una red,Implantación de software específico, Seguridad, rendimiento y recursos. " />
                <modulo id="MP05" nombre="Lenguajes de marcas y sistemas de gestión de información" profesor="Sergio" tecnologias="Programación con XML,Ámbitos de aplicación de XML, Sistemas de gestión de información empresarial" />
                <modulo id="MP06" nombre="Planificación y Administración de redes" profesor="Paco" tecnologias="Introducción a las redes, Administración de dispositivos de red,Administración adelantada de redes." />
            </curso>
            <!--Contenedor del segundo curso -->
            <curso nombre="segundo">
                <modulo id="MP07" nombre="Administración de sistemas gestores de bases de datos" profesor="Paco" tecnologias="Instalación y configuración de gestor de bases de datos,Protección de datos y confidencialidad " />
                <modulo id="MP08" nombre="Administración de sistemas operativos" profesor="Paco" tecnologias="Administración adelantada de sistemas operativos,Automatización de tareas y lenguajes de guiones" />
                <modulo id="MP09" nombre="Empresa e iniciativa emprendedora" profesor="Naza" tecnologias="Empresa e iniciativa emprendedora" />
                <modulo id="MP10" nombre="Implantación de aplicaciones web" profesor="Sergio" tecnologias="Lenguajes de guiones de servidor, Administración de gestores de contenidos" />
                <modulo id="MP11" nombre="Inglés" profesor="Sergio" tecnologias="Inglés técnico" />
                <modulo id="MP12" nombre="Seguridad física y Alta Disponibilidad" profesor="Paco" tecnologias="Seguridad física, lógica y legislación, Seguridad activa y acceso remoto, Cortafuegos y servidores intermediarios,Alta disponibilidad" />
                <modulo id="MP13" nombre="Servicios de red e internet" profesor="Paco" tecnologias="Servicios de nombres y configuración automática,Servicios web y de transferencia de ficheros,Correo electrónico y mensajería, Servicios de audio y vídeo." />
                <modulo id="MP14" nombre="Proyecto de administración de sistemas informáticos en red" profesor="Paco" tecnologias="Proyecto de administración de sistemas informáticos en red" />
                <modulo id="MP15" nombre="FCT" profesor="Paco" tecnologias="Formación en el centros de trabajo" />
            </curso>
        </modulos>
        <!--Ahora agregamos un nuevo "contenedor"-->
        <profesores>
            <!-- Agregamos infomormación del profesor -->
            <profesor id="1">
                <nombre>Sergio</nombre>
                <correo>sergioteacher@yacom</correo>
                <!-- En este apartado agregamos la cantidad de materia que tiene el profesor-->
                <materia>3</materia>
            </profesor>
            <profesor id="2">
                <nombre>Naza</nombre>
                <correo>nazateacher@yahoo.com</correo>
                <materia>2</materia>
            </profesor>
            <profesor id="3">
                <nombre>Paco</nombre>
                <correo>pacoteacher@yahoo.com</correo>
                <materia>10</materia>
            </profesor>
        </profesores>
</ifp>
